#cloud-config

# ipv4 address: ${ipv4_address}

hostname: ${name}

ssh_authorized_keys:
  - ${ssh_key}

coreos:
  units:
    - name: fix-hosts.service
      runtime: true
      command: start
      content: |
        [Service]
        ExecStart=/bin/bash -c "if ! grep -q '${name}' /etc/hosts; then echo ${ipv4_address} ${name} | tee -a /etc/hosts; fi"
    - name: fix-net-bridge.service
      runtime: true
      command: start
      content: |
        [Service]
        ExecStart=/bin/bash -c "modprobe br_netfilter && sysctl net.bridge.bridge-nf-call-iptables=1"
